build_from:
  aarch64: ghcr.io/hassio-addons/base:14.1.0
  amd64: ghcr.io/hassio-addons/base:14.1.0
  armv7: ghcr.io/hassio-addons/base:14.1.0
  armhf: ghcr.io/hassio-addons/base:14.1.0
labels:
  org.opencontainers.image.title: "Benekov MQTT Bridge"
  org.opencontainers.image.description: "Benekov/Climatix HMI → MQTT with Home Assistant Discovery"
  org.opencontainers.image.vendor: "Smitacek"
